### ISSUE TITLE
Assignment 1 submission

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#1]
Hi Carole and Sara, my assignment 1 is ready for submission. The file name for the .rmd and HTML files is: "Assignment 1 KH - for submission." Please let me know if you have any trouble accessing it. Thanks!

**Comment by saratepfer** [comment]
Great job on this, Kristy! 

**Comments on Code**
You don't need lines 17-29 if you're not working with person-level or household-level data.
Also, what you've done to select and combine the indvidual county level data works, but as we discussed, there may be a cleaner and more efficient way to do it if you're interested.  I believe in line 79 you can set county = c("Alameda", "county1", "county2", etc.) (where "county1" and "county2" are replaced with actual county names.) You can then run the following mutation on your dataframe, for each county: mutate(county = case_when(
    str_detect(NAME, "San Francisco", negate = FALSE) ~ "San Francisco")) This will generate the "County" variable that you're looking for for each county. Feel free to swing by office hours if you would like clarification.
