### ISSUE TITLE
Assignment 2 submission is ready for grading

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#2]
Hi Carole & Sara,

Please find my assignment 2 for submission here:
-.rmd: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant%20Assignment%202.Rmd
-HTML: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant-Assignment-2.html

Thank you,
Kristy

**Comment by c-voulgaris** [comment]
Great work! This looks fantastic.

Some detailed comments on your code:

Add a space before lines 27 and 31 to get these to show up in your html file as lists.

You're showing your all your descriptive statistics 3 times: once in a sentence, once in a formatted table, and once as annotation on the histogram. You don't need all three, so you could delete lines 52 - 63, lines 71 - 82, and lines 90 - 136.

Add a space before line 201 so the text doesn't jump onto the same line as the figure before it.

I might delete the last four rows of the majority race table, and maybe you could even add a row with the total (just for the estimates, I'm not sure what that would mean for the confidence intervals), to emphasize that the first five rows represent 100% of the sample.

**Comment by khenrich** [comment]
Thanks so much for this feedback @c-voulgaris ! I have a quick follow up question whenever you have a moment. What are you referring to when you say "majority race table"? Thanks so much.
