### ISSUE TITLE
Assignment 3 submission is ready for grading

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#3]
Hi Carole & Sara, please find my assignment 3 [HTML](https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant-Assignment-3.html) and [.rmd](https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant%20Assignment%203.Rmd) files here. Thanks so much!

**Comment by saratepfer** [comment]
Really nice job on this, Kristy! Both your code and the content look really good! No specific comments from me.
