### ISSUE TITLE
Assignment 4 ready for submission

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#4]
Hi Carole and Sara, here is my assignment 4 for submission:
.rmd: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant%20Assignment%204.Rmd
HTML: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant-Assignment-4.html

Thank you!

**Comment by saratepfer** [comment]
Great job, Kristy! Please see a few comments below.

- I'm a little confused about this sentence: "Marin, Santa Clara, Solano, and Sonoma do have statistically significant relationships to internet access but not at the 95% confidence level." It looks like the p-values for Marin, Santa Clara, Solano, and Sonoma counties are all under 0.05, which means they are statistically significant at the 95% confidence level. Also, how does this sentence fit with the interpretation above it, in point number 2? 
- line 47: It looks like you left out Solano county from this interpretation. I would also add that these increases and decreases are all relative to Alameda county.
- line 51: It looks like your interpretations of your continuous variables are backwards. It should be that every one unit change in the independent variable is associated with an estimated change in the dependent variable.
