### ISSUE TITLE
Assignment 5 questions

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#5]
Hi Carole, Sara, and Cat -

I have a couple of questions on issues that I'm running into with my assignment 5 code found here: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant%20Assignment%205.Rmd

1. In lines 85-116, I am receiving an error when I try to produce a results table: "Unrecognized coefficient names." What am I missing here? I do define my coefficient names in the data frame above, and I *think* I'm attempting to call this same data frame

2. When visualizing the regression results in lines 142-174, I can't seem to change my x axis to include the full range of values, and additionally, it doesn't look like all of my coefficients are being plotted (possibly related to the x scale issue). Any advice?

3. If I try to produce any of the following charts from Carole's tutorial, like in lines 178-190, I receive an error that I "must subset rows with a valid subscript vector...". I've been unable to ascertain what this means. Do you mind assisting?

If it would be easier to hop on a Zoom at any point to fix these, please let me know.

Thank you!
Kristy

**Comment by c-voulgaris** [comment]
I see you submitted your assignment after submitting this issue. Has this been resolved?

**Comment by khenrich** [comment]
Thank you for following up! Sara is working on it for me. I appreciate it.
