### ISSUE TITLE
Assignment 5 is ready for submission

### ISSUE THREAD

**Issue by khenrich** [SES-5215-F2020/kristy_henrich-quant#6]
Hi Carole and Sara,

Please find my assignment 5 submission here.

Thank you!

.rmd: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant%20Assignment%205.Rmd

HTML: https://github.com/SES-5215-F2020/kristy_henrich-quant/blob/master/Quant-Assignment-5.html

**Comment by c-voulgaris** [comment]
This looks good.

On line 81 - you say that some of your results aren't significant, which I understand to meant that some of your coefficients aren't significant. I generally think of the coefficients for all values of a categorical variable collectively. So for example, if there's a significant coefficient for any of your counties, then the county variable is significant. So I'd actually say that all of your independent variables _do_ have a significant relationship with your dependent variable. Also, even if you do have variables in your model that aren't significant, that wouldn't be a problem. Those variables may still contribute to the overall explanatory power of the model.

Some interaction plots are likely to be useful in interpreting the the coefficients in Model 4. Was this the part that you couldn't get working?
